### ISSUE TITLE
get whole folder support

### ISSUE THREAD

**Issue by kernelogic** [textileio/js-powergate-client#147]
Hello I don't see an API to support getting a whole folder staged. Storing a whole folder worked with stageFolder function.

For example in the go client there's 
pow ffs get -t <ffs-token> -f <folder_cid> <output-dir>

**Comment by asutula** [comment]
These should do the trick:

https://textileio.github.io/js-powergate-client/interfaces/ffs.html#stagefolder
https://textileio.github.io/js-powergate-client/interfaces/ffs.html#getfolder

**Comment by asutula** [comment]
If there's something I'm not following in your question, let me know and we can re-open this issue.

**Comment by kernelogic** [comment]
This must be it! Can't believe I missed it.
