### ISSUE TITLE
`fs` module not found

### ISSUE THREAD

**Issue by platocrat** [textileio/js-powergate-client#197]
**Describe the bug**

When I try to import `@textile/powergate-client` v3.0.0 on a page, I get an error that `fs` is not found

I also tried uninstalling and reinstalling powergate, and tried it in diff projects and still get the same issue. So, it must be the powergate-client library.

**To Reproduce**
1. `npm @textile/powergate-client` v3.0.0
2. Import library in a JS page-file
3. Try to render the page with `npm run dev`

**Expected behavior**
Should see no errors when trying to import the library on a page in a JS file. 

**Screenshots**
From my term:
<img width="635" alt="Screen Shot 2020-11-06 at 4 58 35 PM" src="https://user-images.githubusercontent.com/37757724/98422457-4fe85c80-2051-11eb-8c7e-0df0d08ea281.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser:  Brave
 - Version:  

**Additional context**
I'm trying to use the latest v3.0.0 version of the powergate-client

**Comment by asutula** [comment]
Powegate isn't really meant to use in a client side web app... It's mainly used in Node on the the back end. If you want to use it in the browser, you'll have to somehow polyfill `fs` and maybe some other things too. 

But at a high level, I don't think using Powergate JS client from the browser is a wise move. It means you are likely ignoring real application concerns that are usually implemented by an application back end.

**Comment by asutula** [comment]
Authentication and data persistence, are examples.

**Comment by platocrat** [comment]
oh, right. Missing node on the client. Forgot about that
